import black_car from '../img/black_car.png';
import red_car from '../img/red_car.png';
import yellow_car from '../img/yellow_car.png';
import white_car from '../img/white_car.png';

const database = [
    {
        id: 1,
        owner: 'Boris Borisov',
        make: 'Make1',
        model: 'Model1',
        transmission: 'Automatic',
        body_style: 'Coupe',
        year: 2016,
        mileage: 28572,
        picture: red_car,
        condition: 'Perfect',
        city: 'Kyiv',
        body_color: 'Red',
        price: '30000',
    },
    {
        id: 2,
        owner: 'Ivan Ivanov',
        make: 'Make2',
        model: 'Model2',
        transmission: 'Automatic',
        body_style: 'Sedan',
        year: 2010,
        mileage: 18596,
        picture: black_car,
        condition: 'Perfect',
        city: 'Kyiv',
        body_color: 'Black',
        price: '25000',
    },
    {
        id: 3,
        owner: 'Tom Tomich',
        make: 'Make3',
        model: 'Model3',
        transmission: 'Manual',
        body_style: 'Fastback',
        year: 2014,
        mileage: 46385,
        picture: yellow_car,
        condition: 'Normal',
        city: 'Kyiv',
        body_color: 'Yellow',
        price: '40000',
    },
    {
        id: 4,
        owner: 'Dim Dimich',
        make: 'Make4',
        model: 'Model4',
        transmission: 'Automatic',
        body_style: 'Coupe',
        year: 2016,
        mileage: 37597,
        picture: white_car,
        condition: 'Perfect',
        city: 'Kyiv',
        body_color: 'White',
        price: '12000',
    },
    {
        id: 5,
        owner: 'San Sanich',
        make: 'Make5',
        model: 'Model5',
        transmission: 'Automatic',
        body_style: 'Van',
        year: 2019,
        mileage: 29458,
        picture: red_car,
        condition: 'Good',
        city: 'Kyiv',
        body_color: 'Red',
        price: '24000',
    },
    {
        id: 6,
        owner: 'Mark Markov',
        make: 'Make6',
        model: 'Model6',
        transmission: 'Manual',
        body_style: 'Sedan',
        picture: yellow_car,
        year: 2008,
        mileage: 85693,
        condition: 'Perfect',
        city: 'Kyiv',
        body_color: 'Yellow',
        price: '10000',
    },
];

export default database;
